language: node_js
node_js:
  # https://nodejs.org/en/about/releases/
  - "12" # 2022-04-30
  - "14" # 2023-04-30
  - "15" # 2021-06-01
  - "16" # 2024-04-30
install:
  - npm install
script:
  - npm run cover:check
# Send test coverage data to Coveralls:
after_script: "npm run coveralls"
